version: "3.7"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: finametrix-server
    container_name: finametrix-server
    command: npm run start:dev
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: finametrix-client
    container_name: finametrix-client
    command: npm run start:dev
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    ports:
      - "4200:4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
